services:
  session_kicker:
    container_name: session_kicker
    build:
      context: .
      dockerfile: Dockerfile  # Optional if the file is named `Dockerfile`
    restart: unless-stopped
    ports:
      - "8887:80"
    environment:
      JELLYFIN_API_KEY: "b219fb4ea3ed4815ae30b422c7a6e916"
      JELLYFIN_API_URL: "https://watch.gocloudbox.online"

      DONT_KICK_ITEM_TYPE: "movie"
      CHECK_DELAY_IN_SECONDS: 5.0
      MESSAGE_TIME_IN_MILLI: 200
      MAX_WATCH_TIME_IN_SECONDS: 60.0

      # Leave blank to disable
      ITEM_ID_ON_SESSION_KICKED: ""

      WATCH_TIME_OVER_MSG: "You have used up your watch time."
      BLACKLISTED_MSG: "You aren't whitelisted for unlimited watch time."

      RESET_TIME: 00:12

      HTTP_HOST: "session_kicker"
      HTTP_PORT: 80

      MONGO_DB: "session_timer"
      MONGO_HOST: "session_kicker_mongo"

    depends_on:
      - session_kicker_mongo
    networks:
      - intranet

  session_kicker_mongo:
    image: mongo
    container_name: session_kicker_mongo
    restart: unless-stopped
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - session_kicker_mongo_data:/data/db
    networks:
      - intranet

networks:
  intranet:
    external: true

volumes:
  session_kicker_mongo_data:
    driver: local